### PR TITLE
Adds TokenCredential PrincipalId lookup

### PR DESCRIPTION
**Pull request by PascalSenn**
Adds a lookup for the principal id

### CODE REVIEW

**Comment by PascalSenn** [comment]
@microsoft-github-policy-service agree

**Comment by sabbadino** [comment]
Why not use jwttokenhandlet ?
https://learn.microsoft.com/en-us/dotnet/api/system.identitymodel.tokens.jwt.jwtsecuritytokenhandler?view=msal-web-dotnet-latest

**Comment by arealmaas** [comment]
omg looking forward to this 🥰

**Comment by philon-msft** [comment]
@PascalSenn thank you for putting together this PR! I ended up extracting the oid a little differently in #48 with a new dependency on Microsoft.IdentityModel.JsonWebTokens, so I'll close this PR. Let me know if you have any further suggestions.

**Pull request closed without merging**
